use super::super::binary32::{narrow, widen};
use super::Kind;

fn elements(shape: &[i64]) -> Option<usize> {
    shape
        .iter()
        .try_fold(1_usize, |n, &size| {
            n.checked_mul(usize::try_from(size).ok().filter(|&n| n > 0)?)
        })
        .filter(|&n| n <= usize::MAX / 4)
}

/// F32 bits are widened without FP32 arithmetic, so even tiny operands become
/// normal F64 values. Finite products have at most 48 significand bits and fit
/// F64 exactly; quotients are evaluated in F64 before integer F32 rounding.
/// Neither input conversion nor final rounding depends on FP32 flush-to-zero.
pub(in crate::executors::coreml) fn evaluate(
    left: &[u8],
    left_shape: &[i64],
    right: &[u8],
    right_shape: &[i64],
    kind: Kind,
) -> Result<(Vec<i64>, Vec<u8>), &'static str> {
    if elements(left_shape).and_then(|n| n.checked_mul(4)) != Some(left.len())
        || elements(right_shape).and_then(|n| n.checked_mul(4)) != Some(right.len())
    {
        return Err("Float32 binary input does not match its checked shape");
    }
    let rank = left_shape.len().max(right_shape.len());
    let mut shape = vec![1; rank];
    for source in [left_shape, right_shape] {
        for (axis, &size) in source.iter().enumerate() {
            let target = &mut shape[rank - source.len() + axis];
            if *target != size && *target != 1 && size != 1 {
                return Err("Float32 binary actual shapes do not broadcast");
            }
            *target = (*target).max(size);
        }
    }
    let count = elements(&shape).ok_or("Float32 binary output storage exceeds addressable size")?;
    let strides = |source: &[i64]| {
        let mut strides = vec![0; rank];
        let mut stride = 1;
        for axis in (0..source.len()).rev() {
            strides[rank - source.len() + axis] = if source[axis] == 1 { 0 } else { stride };
            stride *= source[axis] as usize;
        }
        strides
    };
    let left_strides = strides(left_shape);
    let right_strides = strides(right_shape);
    let mut result = Vec::new();
    result
        .try_reserve_exact(count * 4)
        .map_err(|_| "Float32 binary output allocation failed")?;
    for index in 0..count {
        let mut remaining = index;
        let (mut a, mut b) = (0, 0);
        for axis in (0..rank).rev() {
            let coordinate = remaining % shape[axis] as usize;
            remaining /= shape[axis] as usize;
            a += coordinate * left_strides[axis];
            b += coordinate * right_strides[axis];
        }
        let a = widen(u32::from_ne_bytes(
            left[a * 4..a * 4 + 4].try_into().unwrap(),
        ));
        let b = widen(u32::from_ne_bytes(
            right[b * 4..b * 4 + 4].try_into().unwrap(),
        ));
        let value = match kind {
            Kind::Multiply => a * b,
            Kind::Divide => a / b,
        };
        result.extend_from_slice(&narrow(value).to_ne_bytes());
    }
    Ok((shape, result))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn oracle() {
        // Generated by exact BigInt rational arithmetic, not the F64 method
        // under test. This stronger local check does not tighten WPT budgets.
        let corpus = include_bytes!("../../../tests/fixtures/coreml_float32_binary/cases.bin");
        assert_eq!(corpus.len(), 29_800 * 16);
        for row in corpus.as_chunks::<16>().0 {
            let words: Vec<_> = row
                .as_chunks::<4>()
                .0
                .iter()
                .map(|n| u32::from_le_bytes(*n))
                .collect();
            let kind = match words[0] {
                0 => Kind::Multiply,
                1 => Kind::Divide,
                _ => panic!("invalid oracle operation"),
            };
            let (_, actual) = evaluate(
                &words[1].to_ne_bytes(),
                &[1],
                &words[2].to_ne_bytes(),
                &[1],
                kind,
            )
            .unwrap();
            let actual = u32::from_ne_bytes(actual.try_into().unwrap());
            if words[3] & 0x7fff_ffff > 0x7f80_0000 {
                assert!(actual & 0x7fff_ffff > 0x7f80_0000);
            } else {
                assert_eq!(
                    actual, words[3],
                    "{kind:?} {:08x} {:08x}",
                    words[1], words[2]
                );
            }
        }
    }

    #[test]
    fn float32_binary_matches_independent_rational_oracle() {
        oracle();
    }

    #[cfg(target_arch = "aarch64")]
    #[test]
    fn float32_binary_is_independent_of_ambient_rounding_flush_and_nan_modes() {
        struct Restore(u64);
        impl Drop for Restore {
            fn drop(&mut self) {
                // Restore the current thread's register even after a failed
                // assertion. Production never changes the caller's FPCR.
                unsafe {
                    std::arch::asm!("msr fpcr, {}", in(reg) self.0);
                }
            }
        }
        let saved: u64;
        unsafe {
            std::arch::asm!("mrs {}, fpcr", out(reg) saved);
        }
        let _restore = Restore(saved);
        for rounding in 0..4 {
            for flush in [0, (1 << 24) | (1 << 19)] {
                for default_nan in [0, 1 << 25] {
                    let mode = (saved & !((3 << 22) | (1 << 24) | (1 << 19) | (1 << 25)))
                        | (rounding << 22)
                        | flush
                        | default_nan;
                    unsafe {
                        std::arch::asm!("msr fpcr, {}", in(reg) mode);
                    }
                    let observed: u64;
                    unsafe {
                        std::arch::asm!("mrs {}, fpcr", out(reg) observed);
                    }
                    assert_eq!(observed, mode);
                    oracle();
                }
            }
        }
    }

    #[test]
    fn float32_binary_validates_storage_and_actual_broadcast() {
        for (left, right) in [
            (&[0][..], &[1][..]),
            (&[-1][..], &[1][..]),
            (&[2][..], &[3][..]),
            (&[i64::MAX][..], &[1][..]),
        ] {
            assert!(evaluate(&[0; 4], left, &[0; 4], right, Kind::Multiply).is_err());
        }
        assert!(evaluate(&[0; 3], &[1], &[0; 4], &[1], Kind::Divide).is_err());
    }
}
